[package]
name = "art-generator"
version = "0.1.0"
authors = ["Zeh Fernando <zeh@zehfernando.com>"]
homepage = "https://github.com/zeh/art-generator"
repository = "https://github.com/zeh/art-generator"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
color_processing = "0.4.1"
image = "0.23.0"
rand = "0.7.3"
structopt = "0.3.9"
