[package]
name = "random-art-generator"
version = "0.2.0"
authors = ["Zeh Fernando <zeh@zehfernando.com>"]
homepage = "https://github.com/zeh/random-art-generator"
repository = "https://github.com/zeh/random-art-generator"
readme = "README.md"
license = "MIT"
edition = "2018"

[dependencies]
color_processing = "0.4.1"
image = "0.23.12"
num_cpus = "1.13.0"
rand = "0.7.3"
structopt = "0.3.9"
