[package]
name = "art-generator"
version = "0.1.0"
authors = ["Zeh Fernando <zeh@zehfernando.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color_processing = "0.4.1"
image = "0.22.4"
rand = "0.7.3"
structopt = "0.3.9"
