name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - '!refs/tags/*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Unit tests
        run: cargo test --verbose

      - name: Format check
        run: cargo fmt -- --check

      - name: Build
        run: cargo build --verbose
